version: '3.1'

services:
  institute-mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "example", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  institute-mongosh:
    image: institute-mongosh
    depends_on:
      institute-mongodb:
        condition: service_healthy
    entrypoint: "mongosh --host institute-mongodb -u root -p example --authenticationDatabase admin agile-learning-institute --eval 'load(\"/src/00-auto.js\")'"

  institute-person-api:
    image: institute-person-api
    restart: always
    ports:
      - 8081:8081
    environment:
      CONNECTION_STRING: mongodb://root:example@institute-mongodb:27017/?tls=false&directConnection=true
      PORT: ":8081"
    depends_on:
      institute-mongosh:
        condition: service_completed_successfully

  institute-person-ui:
    image: institute-person-ui
    restart: always
    environment:
      API_HOST: institute-person-api
      API_PORT: 8081
    ports:
      - 80:80  # Changed the container port to 80
    depends_on:
      - institute-person-api
