version: '3.1'

services:
  institute-mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "example", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 10s
      retries: 5

  institute-mongosh:
    image: ghcr.io/agile-learning-institute/institute-mongosh:latest
    depends_on:
      institute-mongodb:
        condition: service_healthy
    environment:
      - HOST=institute-mongodb
      - USER=root
      - PASSWORD=example
      - AUTH_DB=admin
      - DB_NAME=agile-learning-institute
      - SCRIPT_PATH=/src/migrate.js
      - LOAD_TEST=true
    entrypoint: ["/src/entrypoint.sh"]

  institute-person-api:
    image: ghcr.io/agile-learning-institute/institute-person-api:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      CONNECTION_STRING: mongodb://root:example@institute-mongodb:27017/?tls=false&directConnection=true
      PORT: ":8081"
    depends_on:
      institute-mongosh:
        condition: service_completed_successfully

  institute-person-ui:
    image: ghcr.io/agile-learning-institute/institute-person-ui:latest
    restart: always
    environment:
      API_HOST: institute-person-api
      API_PORT: 8081
    ports:
      - 80:80  # Changed the container port to 80
    depends_on:
      - institute-person-api
